import { ScrollView, StyleSheet, Text, View } from "react-native";
import { router, useLocalSearchParams } from "expo-router";
import { Ionicons } from "@expo/vector-icons";

import { AppScreen } from "@/components/app-screen";
import { BodyText, DisplayText, PrimaryButton, palette } from "@/components/chapman-ui";
import { ScreenHeader } from "@/components/screen-header";
import { ServiceIllustration } from "@/components/service-illustration";
import { getService } from "@/lib/chapman-data";

const serviceDetails: Record<string, { summary: string; steps: string[]; guidance: string[] }> = {
  laundry: { summary: "Choose your clothes and pickup time. We wash, press, fold, and bring them back.", steps: ["Tell us what you are sending", "Choose a pickup time", "Follow your order until it returns"], guidance: ["Small items from ₵3", "Shirts and trousers from ₵7", "Express care adds ₵10 per item"] },
  cleaning: { summary: "Tell us about your space. We check what it needs, then send a clear quote before work starts.", steps: ["Choose the type of space", "Pick a day for assessment", "Approve the quote before we start"], guidance: ["One bedroom from ₵450", "Three bedrooms from ₵850", "Minimum service ₵500"] },
  fumigation: { summary: "Tell us the pest problem and the kind of building. Our team will recommend the right treatment.", steps: ["Tell us the pest problem", "Choose a suitable day", "Receive a clear treatment quote"], guidance: ["Cockroach care from ₵250", "Bedbug care from ₵500", "Minimum service ₵300"] },
  detailing: { summary: "Choose the care your car needs. We confirm the finish, the time, and the price before service starts.", steps: ["Tell us your car type", "Choose basic or full detail", "Confirm a service time"], guidance: ["Sedan wash ₵45", "SUV wash ₵60", "Full detail from ₵180"] },
  fabric: { summary: "Choose the furniture or carpet that needs care. We check the fabric and give you the right price.", steps: ["Tell us what needs cleaning", "Choose extra stain or odour care", "Confirm the final service price"], guidance: ["Sofa care from ₵60", "Sofa service minimum ₵150", "Carpet service minimum ₵200"] },
  polytank: { summary: "Tell us your tank size. We plan the cleaning visit so your water storage gets the right care.", steps: ["Choose your tank size", "Choose a service day", "Follow the visit from confirmation"], guidance: ["Small tank ₵150", "Medium tank ₵350", "Large tank ₵600"] },
  contract: { summary: "Tell us about your facility. We build a regular cleaning plan that fits your week and your budget.", steps: ["Tell us about the facility", "Receive a monthly plan", "Track each planned visit"], guidance: ["Small office from ₵600 monthly", "Schools from ₵1,200 monthly", "Clinics from ₵1,500 monthly"] },
};

export default function ServiceDetailScreen() {
  const { id } = useLocalSearchParams<{ id: string }>();
  const service = getService(id);
  const detail = serviceDetails[service.id] ?? serviceDetails.cleaning;
  const isLaundry = service.id === "laundry";
  const beginBooking = () => {
    if (isLaundry) router.push("/booking/laundry" as never);
    else router.push({ pathname: "/booking/request-quote" as never, params: { serviceId: service.id } });
  };

  return <AppScreen><View style={styles.page}><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><ScreenHeader title={service.shortTitle} /><ServiceIllustration serviceId={service.id} /><View style={styles.intro}><Text style={styles.label}>ABOUT THIS SERVICE</Text><DisplayText style={styles.title}>{service.title}</DisplayText><BodyText style={styles.summary}>{detail.summary}</BodyText></View><View style={styles.steps}><Text style={styles.sectionTitle}>How it works</Text>{detail.steps.map((step, index) => <View key={step} style={styles.step}><View style={styles.stepNumber}><Text style={styles.stepNumberText}>{index + 1}</Text></View><Text style={styles.stepText}>{step}</Text></View>)}</View><View style={styles.priceSection}><View style={styles.priceHeader}><View><Text style={styles.label}>SIMPLE PRICE GUIDE</Text><Text style={styles.priceTitle}>What it starts from</Text></View><Ionicons name="receipt-outline" size={21} color={palette.blue} /></View>{detail.guidance.map((item) => <View key={item} style={styles.priceLine}><View style={styles.priceDot} /><Text style={styles.priceLineText}>{item}</Text></View>)}</View><View style={styles.paymentNote}><Ionicons name="wallet-outline" size={20} color={palette.blue} /><View style={styles.paymentCopy}><Text style={styles.paymentTitle}>Choose how you want to pay</Text><Text style={styles.paymentText}>{isLaundry ? "Mobile Money, card, or cash options appear before you confirm." : "You can choose Mobile Money, card, cash, or pay after the quote is approved."}</Text></View></View></ScrollView><View style={styles.bottomBar}><PrimaryButton label={service.actionLabel} icon="arrow-forward" onPress={beginBooking} /></View></View></AppScreen>;
}

const styles = StyleSheet.create({ page: { flex: 1, backgroundColor: palette.canvas }, content: { padding: 20, paddingTop: 12, paddingBottom: 110, gap: 19 }, intro: { gap: 7, paddingHorizontal: 2 }, label: { color: "#5871B5", fontFamily: "Inter_700Bold", fontSize: 9, letterSpacing: 1.2 }, title: { fontSize: 26, lineHeight: 33 }, summary: { fontSize: 14, lineHeight: 21, maxWidth: 330 }, steps: { paddingVertical: 2, gap: 12 }, sectionTitle: { color: palette.ink, fontFamily: "PlusJakartaSans_800ExtraBold", fontSize: 18, marginBottom: 2 }, step: { flexDirection: "row", alignItems: "center", gap: 11 }, stepNumber: { width: 27, height: 27, borderRadius: 14, backgroundColor: "#E8EEFF", alignItems: "center", justifyContent: "center" }, stepNumberText: { color: palette.blue, fontFamily: "Inter_700Bold", fontSize: 12 }, stepText: { flex: 1, color: palette.ink, fontFamily: "Inter_500Medium", fontSize: 13, lineHeight: 18 }, priceSection: { padding: 16, borderRadius: 19, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: palette.border, gap: 10 }, priceHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingBottom: 4 }, priceTitle: { color: palette.ink, fontFamily: "Inter_700Bold", fontSize: 16, marginTop: 3 }, priceLine: { flexDirection: "row", alignItems: "center", gap: 8 }, priceDot: { width: 5, height: 5, borderRadius: 3, backgroundColor: palette.blue }, priceLineText: { color: palette.muted, fontFamily: "Inter_500Medium", fontSize: 12 }, paymentNote: { padding: 14, borderRadius: 17, backgroundColor: "#EEF3FF", flexDirection: "row", gap: 10, alignItems: "flex-start" }, paymentCopy: { flex: 1, gap: 3 }, paymentTitle: { color: palette.ink, fontFamily: "Inter_700Bold", fontSize: 13 }, paymentText: { color: palette.muted, fontFamily: "Inter_400Regular", fontSize: 12, lineHeight: 18 }, bottomBar: { position: "absolute", bottom: 0, left: 0, right: 0, paddingHorizontal: 20, paddingTop: 12, paddingBottom: 18, backgroundColor: "rgba(248,249,250,0.98)", borderTopWidth: 1, borderTopColor: palette.border } });
