import { ScrollView, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { router, useLocalSearchParams } from "expo-router";
import { Ionicons } from "@expo/vector-icons";

import { AppScreen } from "@/components/app-screen";
import { BodyText, DisplayText, PrimaryButton, StatusPill, palette } from "@/components/chapman-ui";
import { ScreenHeader } from "@/components/screen-header";
import { useBookingStore } from "@/lib/booking-store";

export default function BookingDetailScreen() {
  const { id } = useLocalSearchParams<{ id: string }>();
  const { bookings, quotes } = useBookingStore();
  const booking = bookings.find((item) => item.id === id);
  const quote = quotes.find((item) => item.id === id);
  const isQuote = Boolean(quote);
  const title = booking?.serviceTitle ?? quote?.serviceTitle ?? "Your Chapman request";
  const status = isQuote ? "assessment requested" : booking?.status.replace("-", " ") ?? "confirmed";

  return <AppScreen><View style={styles.page}><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><ScreenHeader title="Booking details" /><View style={styles.hero}><View style={styles.successMark}><Ionicons name={isQuote ? "document-text-outline" : "checkmark"} size={30} color="#FFFFFF" /></View><StatusPill label={status} tone={isQuote ? "orange" : "green"} /><DisplayText style={styles.heroTitle}>{isQuote ? "Your assessment is in motion." : "Your booking is confirmed."}</DisplayText><BodyText style={styles.heroBody}>{isQuote ? "A Chapman coordinator will review your request and contact you with the appropriate next step." : "We have reserved your pickup window and will keep you informed at each milestone."}</BodyText><Text style={styles.reference}>{id}</Text></View><View style={styles.infoCard}><Text style={styles.infoLabel}>SERVICE</Text><Text style={styles.infoTitle}>{title}</Text><Text style={styles.infoMeta}>{isQuote ? `${quote?.propertyType} · ${quote?.preference}` : booking?.scheduledFor}</Text></View>{!isQuote ? <View style={styles.timelineCard}><Text style={styles.timelineTitle}>Service timeline</Text>{["Booking confirmed", "Specialist assigned", "Care in progress", "Completed"].map((step, index) => <View key={step} style={styles.timelineRow}><View style={styles.timelineRail}><View style={[styles.timelineDot, index === 0 && styles.timelineDotActive]}>{index === 0 ? <Ionicons name="checkmark" size={11} color="#FFFFFF" /> : null}</View>{index < 3 ? <View style={styles.timelineLine} /> : null}</View><View style={styles.timelineCopy}><Text style={[styles.timelineStep, index === 0 && styles.timelineStepActive]}>{step}</Text><Text style={styles.timelineMeta}>{index === 0 ? "Your time is reserved" : "We will update you here"}</Text></View></View>)}</View> : <View style={styles.assessmentCard}><Ionicons name="call-outline" size={22} color={palette.orange} /><View style={styles.assessmentCopy}><Text style={styles.assessmentTitle}>We will contact you</Text><Text style={styles.assessmentText}>Expect a coordinated assessment conversation before a final quote is sent.</Text></View></View>}</ScrollView><View style={styles.bottom}>{isQuote ? <PrimaryButton label="Back to bookings" icon="calendar-outline" onPress={() => router.replace("/bookings" as never)} /> : <PrimaryButton label="Track live" icon="navigate-outline" onPress={() => router.push("/(tabs)/chat" as never)} />}</View></View></AppScreen>;
}

const styles = StyleSheet.create({ page: { flex: 1, backgroundColor: palette.canvas }, content: { padding: 20, paddingTop: 12, paddingBottom: 106, gap: 17 }, hero: { padding: 20, alignItems: "center", backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: palette.border, borderRadius: 23, gap: 10 }, successMark: { width: 66, height: 66, borderRadius: 25, backgroundColor: palette.green, alignItems: "center", justifyContent: "center" }, heroTitle: { textAlign: "center", fontSize: 24, lineHeight: 30, marginTop: 3 }, heroBody: { textAlign: "center", maxWidth: 290, fontSize: 12, lineHeight: 18 }, reference: { color: palette.muted, fontFamily: "Inter_700Bold", fontSize: 11, letterSpacing: 0.8, marginTop: 2 }, infoCard: { padding: 16, borderRadius: 20, backgroundColor: "#EEF2FF", gap: 4 }, infoLabel: { color: palette.blue, fontFamily: "Inter_700Bold", fontSize: 9, letterSpacing: 1.1 }, infoTitle: { color: palette.ink, fontFamily: "Inter_700Bold", fontSize: 15 }, infoMeta: { color: palette.muted, fontFamily: "Inter_400Regular", fontSize: 12 }, timelineCard: { padding: 17, borderRadius: 20, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: palette.border, gap: 12 }, timelineTitle: { color: palette.ink, fontFamily: "PlusJakartaSans_800ExtraBold", fontSize: 18 }, timelineRow: { flexDirection: "row", gap: 10, minHeight: 51 }, timelineRail: { alignItems: "center", width: 21 }, timelineDot: { width: 20, height: 20, borderRadius: 10, backgroundColor: "#E3E6EC", alignItems: "center", justifyContent: "center" }, timelineDotActive: { backgroundColor: palette.green }, timelineLine: { width: 2, flex: 1, backgroundColor: "#E3E6EC" }, timelineCopy: { gap: 2, flex: 1 }, timelineStep: { color: palette.muted, fontFamily: "Inter_600SemiBold", fontSize: 13 }, timelineStepActive: { color: palette.ink }, timelineMeta: { color: "#8C91A1", fontFamily: "Inter_400Regular", fontSize: 11 }, assessmentCard: { padding: 15, borderRadius: 19, borderWidth: 1, borderColor: "#FFE1D1", backgroundColor: "#FFF5F0", flexDirection: "row", gap: 11, alignItems: "flex-start" }, assessmentCopy: { flex: 1, gap: 3 }, assessmentTitle: { color: palette.ink, fontFamily: "Inter_700Bold", fontSize: 14 }, assessmentText: { color: palette.muted, fontFamily: "Inter_400Regular", fontSize: 12, lineHeight: 18 }, bottom: { position: "absolute", bottom: 0, left: 0, right: 0, padding: 20, paddingTop: 12, paddingBottom: 18, backgroundColor: "rgba(248,249,250,0.98)", borderTopWidth: 1, borderTopColor: palette.border } });
