import { useMemo } from "react";
import { ScrollView, StyleSheet, Switch, Text, TouchableOpacity, View } from "react-native";
import { router } from "expo-router";
import { Ionicons } from "@expo/vector-icons";

import { AppScreen } from "@/components/app-screen";
import { BodyText, DisplayText, PrimaryButton, palette } from "@/components/chapman-ui";
import { ScreenHeader } from "@/components/screen-header";
import { LAUNDRY_ITEMS, formatGhs } from "@/lib/chapman-data";
import { useBookingStore } from "@/lib/booking-store";
import { haptic } from "@/lib/haptics";

export default function LaundryBookingScreen() {
  const { cart, express, setExpress, updateLaundryQuantity, cartCount, laundrySubtotal, expressFee } = useBookingStore();
  const quantityFor = (id: string) => cart.find((line) => line.item.id === id)?.quantity ?? 0;
  const groupedItems = useMemo(() => LAUNDRY_ITEMS.reduce<Record<string, typeof LAUNDRY_ITEMS>>((groups, item) => ({ ...groups, [item.category]: [...(groups[item.category] ?? []), item] }), {}), []);
  const total = laundrySubtotal + expressFee + (cartCount ? 20 : 0);

  return <AppScreen><View style={styles.page}><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><ScreenHeader title="Build your laundry" subtitle="Transparent per-item pricing" /><View style={styles.intro}><View style={styles.introIcon}><Ionicons name="shirt-outline" size={24} color="#FFFFFF" /></View><View style={styles.introCopy}><DisplayText style={styles.introTitle}>What are we caring for?</DisplayText><BodyText style={styles.introBody}>Add items to see your exact garment-care price before you book.</BodyText></View></View>{Object.entries(groupedItems).map(([category, items]) => <View key={category} style={styles.category}><Text style={styles.categoryTitle}>{category}</Text><View style={styles.itemList}>{items.map((item) => { const quantity = quantityFor(item.id); return <View key={item.id} style={styles.itemRow}><View><Text style={styles.itemName}>{item.name}</Text><Text style={styles.itemPrice}>{formatGhs(item.price)} each</Text></View><View style={styles.stepper}><TouchableOpacity disabled={quantity === 0} onPress={() => { haptic.selection(); updateLaundryQuantity(item, quantity - 1); }} style={[styles.stepperButton, quantity === 0 && styles.stepperDisabled]}><Ionicons name="remove" size={17} color={quantity === 0 ? "#B6BAC6" : palette.blue} /></TouchableOpacity><Text style={styles.quantity}>{quantity}</Text><TouchableOpacity onPress={() => { haptic.selection(); updateLaundryQuantity(item, quantity + 1); }} style={styles.stepperButton}><Ionicons name="add" size={17} color={palette.blue} /></TouchableOpacity></View></View>; })}</View></View>)}<View style={styles.expressCard}><View style={styles.expressIcon}><Ionicons name="flash" size={20} color={palette.orange} /></View><View style={styles.expressCopy}><Text style={styles.expressTitle}>Express care</Text><Text style={styles.expressMeta}>Priority turnaround · ₵10 per item</Text></View><Switch value={express} onValueChange={(value) => { haptic.medium(); setExpress(value); }} trackColor={{ false: "#D8DBE4", true: "#FFBE92" }} thumbColor={express ? palette.orange : "#FFFFFF"} /></View></ScrollView><View style={styles.summary}><View style={styles.summaryText}><Text style={styles.summaryLabel}>{cartCount ? `${cartCount} item${cartCount === 1 ? "" : "s"} selected` : "Select items to continue"}</Text><Text style={styles.summaryTotal}>{cartCount ? formatGhs(total) : "₵0"}</Text></View><PrimaryButton label="Review booking" icon="arrow-forward" disabled={!cartCount} onPress={() => router.push("/checkout" as never)} style={styles.summaryButton} /></View></View></AppScreen>;
}

const styles = StyleSheet.create({ page: { flex: 1, backgroundColor: palette.canvas }, content: { padding: 20, paddingTop: 12, paddingBottom: 110, gap: 17 }, intro: { padding: 16, borderRadius: 21, backgroundColor: "#003EC7", flexDirection: "row", gap: 12, alignItems: "center" }, introIcon: { width: 47, height: 47, borderRadius: 16, backgroundColor: "rgba(255,255,255,0.16)", alignItems: "center", justifyContent: "center" }, introCopy: { flex: 1, gap: 4 }, introTitle: { color: "#FFFFFF", fontSize: 20, lineHeight: 26 }, introBody: { color: "#DDE1FF", fontSize: 12, lineHeight: 17 }, category: { gap: 8 }, categoryTitle: { color: palette.blue, fontFamily: "Inter_700Bold", fontSize: 10, letterSpacing: 1.1, paddingHorizontal: 2 }, itemList: { backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: palette.border, borderRadius: 18, overflow: "hidden" }, itemRow: { minHeight: 65, paddingHorizontal: 14, flexDirection: "row", alignItems: "center", justifyContent: "space-between", borderBottomWidth: 1, borderBottomColor: "#EEF0F4" }, itemName: { color: palette.ink, fontFamily: "Inter_600SemiBold", fontSize: 13 }, itemPrice: { color: palette.muted, fontFamily: "Inter_400Regular", fontSize: 11, marginTop: 3 }, stepper: { flexDirection: "row", alignItems: "center", gap: 8 }, stepperButton: { width: 31, height: 31, borderRadius: 10, backgroundColor: "#EEF2FF", alignItems: "center", justifyContent: "center" }, stepperDisabled: { backgroundColor: "#F1F2F5" }, quantity: { color: palette.ink, fontFamily: "Inter_700Bold", fontSize: 14, minWidth: 15, textAlign: "center" }, expressCard: { padding: 14, borderRadius: 18, backgroundColor: "#FFF5F0", borderWidth: 1, borderColor: "#FFE1D1", flexDirection: "row", alignItems: "center", gap: 10 }, expressIcon: { width: 38, height: 38, borderRadius: 13, backgroundColor: "#FFF0E8", alignItems: "center", justifyContent: "center" }, expressCopy: { flex: 1, gap: 2 }, expressTitle: { color: palette.ink, fontFamily: "Inter_700Bold", fontSize: 13 }, expressMeta: { color: palette.muted, fontFamily: "Inter_400Regular", fontSize: 11 }, summary: { position: "absolute", left: 0, right: 0, bottom: 0, padding: 15, paddingHorizontal: 20, paddingBottom: 18, flexDirection: "row", gap: 12, alignItems: "center", backgroundColor: "rgba(248,249,250,0.98)", borderTopWidth: 1, borderTopColor: palette.border }, summaryText: { flex: 1, gap: 2 }, summaryLabel: { color: palette.muted, fontFamily: "Inter_500Medium", fontSize: 11 }, summaryTotal: { color: palette.ink, fontFamily: "PlusJakartaSans_800ExtraBold", fontSize: 19 }, summaryButton: { minWidth: 164 } });
