import { StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { router } from "expo-router";
import { Ionicons } from "@expo/vector-icons";
import { LinearGradient } from "expo-linear-gradient";

import { AppScreen } from "@/components/app-screen";
import { ChapmanMark, DisplayText, PrimaryButton, palette } from "@/components/chapman-ui";

export default function WelcomeScreen() {
  return <AppScreen dark edges={["top", "bottom", "left", "right"]}><LinearGradient colors={["#001452", "#003EC7"]} style={styles.page}><View style={styles.brand}><ChapmanMark inverted size={58} /><View><Text style={styles.brandName}>CHAPMAN</Text><Text style={styles.brandSub}>PRESTIGE</Text></View></View><View style={styles.content}><View style={styles.welcomeIcon}><Ionicons name="sparkles" size={48} color="#FFFFFF" /></View><Text style={styles.eyebrow}>WELCOME TO A BETTER ROUTINE</Text><DisplayText style={styles.title}>What needs more care today?</DisplayText><Text style={styles.body}>Create an account when you are ready, or explore every service as a guest.</Text></View><View style={styles.actions}><PrimaryButton label="Continue with phone" icon="arrow-forward" onPress={() => router.push("/auth/phone" as never)} /><TouchableOpacity onPress={() => router.replace("/(tabs)" as never)} style={styles.guest}><Text style={styles.guestText}>Continue as guest</Text></TouchableOpacity><Text style={styles.terms}>By continuing, you agree to receive service updates for your bookings.</Text></View></LinearGradient></AppScreen>;
}

const styles = StyleSheet.create({ page: { flex: 1, padding: 24, justifyContent: "space-between" }, brand: { flexDirection: "row", alignItems: "center", gap: 12 }, brandName: { color: "#FFFFFF", fontFamily: "PlusJakartaSans_800ExtraBold", fontSize: 18, letterSpacing: 1.3 }, brandSub: { color: "#BFCBFF", fontFamily: "Inter_700Bold", fontSize: 10, letterSpacing: 2.4, marginTop: 1 }, content: { alignItems: "center", gap: 14, paddingHorizontal: 8 }, welcomeIcon: { width: 106, height: 106, borderRadius: 38, backgroundColor: "rgba(255,255,255,0.14)", alignItems: "center", justifyContent: "center", marginBottom: 8 }, eyebrow: { color: "#BFCBFF", fontFamily: "Inter_700Bold", fontSize: 10, letterSpacing: 1.3 }, title: { color: "#FFFFFF", textAlign: "center", fontSize: 30, lineHeight: 38 }, body: { color: "#DDE1FF", fontFamily: "Inter_400Regular", fontSize: 14, lineHeight: 21, textAlign: "center", maxWidth: 310 }, actions: { gap: 13 }, guest: { height: 50, borderRadius: 16, alignItems: "center", justifyContent: "center", borderWidth: 1, borderColor: "rgba(255,255,255,0.32)" }, guestText: { color: "#FFFFFF", fontFamily: "Inter_700Bold", fontSize: 14 }, terms: { color: "#BFCBFF", fontFamily: "Inter_400Regular", fontSize: 10, lineHeight: 15, textAlign: "center" } });
