import { Image, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { router } from "expo-router";
import { Ionicons } from "@expo/vector-icons";

import { AppScreen } from "@/components/app-screen";
import { DisplayText, palette } from "@/components/chapman-ui";
import { haptic } from "@/lib/haptics";

export default function WelcomeScreen() {
  const continueAsGuest = () => { haptic.light(); router.replace("/(tabs)" as never); };
  return <AppScreen edges={["top", "bottom", "left", "right"]}><View style={styles.page}><Image source={require("@/assets/images/cpl-wordmark.png")} resizeMode="contain" style={styles.wordmark} /><View style={styles.content}><View style={styles.imageFrame}><Image source={{ uri: "/manus-storage/chapman-workers-hero_422ce2ab.jpg" }} resizeMode="cover" style={styles.image} /></View><View style={styles.copy}><Text style={styles.eyebrow}>WELCOME TO CHAPMAN</Text><DisplayText style={styles.title}>What can feel better today?</DisplayText><Text style={styles.body}>Explore the services that give your day more room to breathe. Create an account whenever you are ready.</Text></View></View><View style={styles.actions}><TouchableOpacity onPress={continueAsGuest} activeOpacity={0.88} style={styles.primary}><Text style={styles.primaryText}>Continue with phone</Text><Ionicons name="arrow-forward" size={19} color="#FFFFFF" /></TouchableOpacity><TouchableOpacity onPress={continueAsGuest} activeOpacity={0.72} style={styles.guest}><Text style={styles.guestText}>Explore as a guest</Text></TouchableOpacity><Text style={styles.terms}>By continuing, you agree to receive updates relevant to your Chapman bookings.</Text></View></View></AppScreen>;
}

const styles = StyleSheet.create({ page: { flex: 1, backgroundColor: "#F8F8F6", paddingHorizontal: 22, paddingTop: 12, paddingBottom: 16, justifyContent: "space-between" }, wordmark: { width: 128, height: 42 }, content: { gap: 26, marginTop: 15 }, imageFrame: { height: 286, borderRadius: 26, overflow: "hidden", backgroundColor: "#DCE6FF" }, image: { width: "100%", height: "100%" }, copy: { gap: 9, paddingHorizontal: 2 }, eyebrow: { color: "#5871B5", fontFamily: "Inter_700Bold", fontSize: 9, letterSpacing: 1.4 }, title: { fontSize: 29, lineHeight: 37, maxWidth: 320 }, body: { color: "#586378", fontFamily: "Inter_400Regular", fontSize: 14, lineHeight: 21, maxWidth: 320 }, actions: { gap: 11 }, primary: { height: 54, borderRadius: 16, backgroundColor: palette.blue, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 10 }, primaryText: { color: "#FFFFFF", fontFamily: "Inter_700Bold", fontSize: 15 }, guest: { height: 47, alignItems: "center", justifyContent: "center" }, guestText: { color: palette.blue, fontFamily: "Inter_700Bold", fontSize: 14 }, terms: { color: "#8B94A6", fontFamily: "Inter_400Regular", fontSize: 10, lineHeight: 15, textAlign: "center", paddingHorizontal: 16 } });
