import { Image, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { router } from "expo-router";
import { LinearGradient } from "expo-linear-gradient";

import { AppScreen } from "@/components/app-screen";
import { ChapmanMark, DisplayText, PrimaryButton, palette } from "@/components/chapman-ui";

export default function WelcomeScreen() {
  return <AppScreen edges={["top", "bottom", "left", "right"]}><LinearGradient colors={[palette.canvas, "#FFF3CE", "#E4F3E8"]} locations={[0, 0.56, 1]} style={styles.page}><View style={styles.brand}><ChapmanMark size={58} /></View><View style={styles.content}><Image source={require("@/assets/images/service-care-collage.png")} resizeMode="contain" style={styles.serviceCollage} /><Text style={styles.eyebrow}>WELCOME TO A BETTER ROUTINE</Text><DisplayText style={styles.title}>What needs more care today?</DisplayText><Text style={styles.body}>Create an account when you are ready, or explore every service as a guest.</Text></View><View style={styles.actions}><PrimaryButton label="Continue with phone" icon="arrow-forward" onPress={() => router.push("/auth/phone" as never)} /><TouchableOpacity onPress={() => router.replace("/(tabs)" as never)} style={styles.guest}><Text style={styles.guestText}>Continue as guest</Text></TouchableOpacity><Text style={styles.terms}>By continuing, you agree to receive service updates for your bookings.</Text></View></LinearGradient></AppScreen>;
}

const styles = StyleSheet.create({ page: { flex: 1, padding: 24, justifyContent: "space-between", overflow: "hidden" }, brand: { flexDirection: "row", alignItems: "center" }, content: { alignItems: "center", gap: 13, paddingHorizontal: 8 }, serviceCollage: { width: 234, height: 250, marginBottom: 2 }, eyebrow: { color: palette.green, fontFamily: "Inter_700Bold", fontSize: 10, letterSpacing: 1.3 }, title: { color: palette.deep, textAlign: "center", fontSize: 30, lineHeight: 38 }, body: { color: palette.muted, fontFamily: "Inter_400Regular", fontSize: 14, lineHeight: 21, textAlign: "center", maxWidth: 310 }, actions: { gap: 13 }, guest: { height: 50, borderRadius: 16, alignItems: "center", justifyContent: "center", borderWidth: 1, borderColor: "#9DD3B8", backgroundColor: "rgba(255,255,255,0.55)" }, guestText: { color: palette.green, fontFamily: "Inter_700Bold", fontSize: 14 }, terms: { color: palette.muted, fontFamily: "Inter_400Regular", fontSize: 10, lineHeight: 15, textAlign: "center" } });
