import { ScrollView, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { Ionicons } from "@expo/vector-icons";

import { AppScreen } from "@/components/app-screen";
import { BodyText, DisplayText, palette } from "@/components/chapman-ui";

const threads = [
  { id: "support", name: "Chapman Concierge", message: "Hello! What can we help you arrange today?", time: "Now", initials: "CP", color: "#003EC7", unread: 1 },
  { id: "welcome", name: "Welcome to Chapman", message: "Your care team is ready whenever you are.", time: "Today", initials: "C", color: "#FE6B00", unread: 0 },
];

export default function ChatScreen() {
  return <AppScreen><View style={styles.page}><View style={styles.header}><View><Text style={styles.eyebrow}>CONVERSATIONS</Text><DisplayText style={styles.title}>Chat</DisplayText></View><TouchableOpacity style={styles.compose}><Ionicons name="create-outline" size={21} color={palette.blue} /></TouchableOpacity></View><View style={styles.bookingPrompt}><View style={styles.promptIcon}><Ionicons name="headset-outline" size={19} color="#FFFFFF" /></View><View style={styles.promptCopy}><Text style={styles.promptTitle}>Need a hand deciding?</Text><Text style={styles.promptMeta}>Ask our concierge about any service or price.</Text></View><Ionicons name="arrow-forward" size={17} color={palette.blue} /></View><ScrollView contentContainerStyle={styles.threadList} showsVerticalScrollIndicator={false}>{threads.map((thread) => <TouchableOpacity key={thread.id} style={styles.thread} activeOpacity={0.75}><View style={[styles.threadAvatar, { backgroundColor: `${thread.color}18` }]}><Text style={[styles.threadInitials, { color: thread.color }]}>{thread.initials}</Text>{thread.unread ? <View style={[styles.threadDot, { backgroundColor: thread.color }]} /> : null}</View><View style={styles.threadCopy}><View style={styles.threadTop}><Text style={styles.threadName}>{thread.name}</Text><Text style={styles.threadTime}>{thread.time}</Text></View><Text numberOfLines={1} style={styles.threadMessage}>{thread.message}</Text></View>{thread.unread ? <View style={styles.unreadCount}><Text style={styles.unreadText}>{thread.unread}</Text></View> : null}</TouchableOpacity>)}<View style={styles.infoCard}><Ionicons name="lock-closed-outline" size={18} color={palette.blue} /><BodyText style={styles.infoCopy}>Your booking conversations will stay organised here, with service context attached for faster support.</BodyText></View></ScrollView></View></AppScreen>;
}

const styles = StyleSheet.create({ page: { flex: 1, backgroundColor: palette.canvas, paddingHorizontal: 20, paddingTop: 18 }, header: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, eyebrow: { color: palette.blue, fontFamily: "Inter_700Bold", fontSize: 10, letterSpacing: 1.2 }, title: { fontSize: 30, marginTop: 2 }, compose: { width: 42, height: 42, borderRadius: 14, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: palette.border, alignItems: "center", justifyContent: "center" }, bookingPrompt: { marginTop: 22, padding: 14, backgroundColor: "#EEF2FF", borderRadius: 18, flexDirection: "row", alignItems: "center", gap: 10 }, promptIcon: { width: 37, height: 37, borderRadius: 13, backgroundColor: palette.blue, alignItems: "center", justifyContent: "center" }, promptCopy: { flex: 1, gap: 2 }, promptTitle: { color: palette.ink, fontFamily: "Inter_700Bold", fontSize: 13 }, promptMeta: { color: palette.muted, fontFamily: "Inter_400Regular", fontSize: 11, lineHeight: 15 }, threadList: { paddingTop: 20, gap: 8, paddingBottom: 32 }, thread: { backgroundColor: "#FFFFFF", borderRadius: 18, padding: 13, borderWidth: 1, borderColor: palette.border, flexDirection: "row", alignItems: "center", gap: 12 }, threadAvatar: { width: 48, height: 48, borderRadius: 17, alignItems: "center", justifyContent: "center" }, threadInitials: { fontFamily: "PlusJakartaSans_800ExtraBold", fontSize: 15 }, threadDot: { position: "absolute", right: -2, top: -2, width: 12, height: 12, borderRadius: 6, borderWidth: 2, borderColor: "#FFFFFF" }, threadCopy: { flex: 1, gap: 4 }, threadTop: { flexDirection: "row", justifyContent: "space-between", gap: 8 }, threadName: { color: palette.ink, fontFamily: "Inter_700Bold", fontSize: 14 }, threadTime: { color: palette.muted, fontFamily: "Inter_500Medium", fontSize: 10 }, threadMessage: { color: palette.muted, fontFamily: "Inter_400Regular", fontSize: 12 }, unreadCount: { minWidth: 19, height: 19, paddingHorizontal: 5, borderRadius: 10, backgroundColor: palette.blue, alignItems: "center", justifyContent: "center" }, unreadText: { color: "#FFFFFF", fontFamily: "Inter_700Bold", fontSize: 10 }, infoCard: { marginTop: 10, padding: 14, borderRadius: 17, borderWidth: 1, borderColor: "#CFD8FF", flexDirection: "row", gap: 10, alignItems: "flex-start", backgroundColor: "#F8FAFF" }, infoCopy: { flex: 1, fontSize: 12, lineHeight: 18 } });
