import { ScrollView, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { Ionicons } from "@expo/vector-icons";

import { AppScreen } from "@/components/app-screen";
import { BodyText, DisplayText, StatusPill, palette } from "@/components/chapman-ui";
import { WORKERS } from "@/lib/chapman-data";

export default function WorkersScreen() {
  return <AppScreen><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><View><Text style={styles.eyebrow}>WORKER MARKETPLACE</Text><DisplayText style={styles.title}>Skilled help, when you need it.</DisplayText><BodyText style={styles.subtitle}>Request verified professionals for the practical jobs around your home or facility.</BodyText></View><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.categoryRow}><View style={styles.categorySelected}><Text style={styles.categorySelectedText}>All workers</Text></View>{["Electricians", "Plumbers", "Painters", "Cleaners"].map((label) => <View key={label} style={styles.category}><Text style={styles.categoryText}>{label}</Text></View>)}</ScrollView><View style={styles.liveCard}><View style={styles.liveIcon}><Ionicons name="flash" size={17} color="#FFFFFF" /></View><View style={styles.liveCopy}><Text style={styles.liveTitle}>Live availability</Text><Text style={styles.liveMeta}>Workers refresh their schedule throughout the day.</Text></View><StatusPill label="LIVE" tone="orange" /></View><View style={styles.list}>{WORKERS.map((worker) => <TouchableOpacity key={worker.id} activeOpacity={0.82} style={styles.workerCard}><View style={[styles.workerAvatar, { backgroundColor: `${worker.color}1A` }]}><Text style={[styles.workerInitials, { color: worker.color }]}>{worker.initials}</Text><View style={[styles.verified, { backgroundColor: worker.color }]}><Ionicons name="checkmark" size={9} color="#FFFFFF" /></View></View><View style={styles.workerCopy}><View style={styles.workerTop}><Text style={styles.workerName}>{worker.name}</Text><Ionicons name="chevron-forward" size={18} color="#7A7E8D" /></View><Text style={styles.workerSkill}>{worker.skill}</Text><View style={styles.ratingRow}><Ionicons name="star" size={13} color="#F6A800" /><Text style={styles.rating}>{worker.rating}</Text><Text style={styles.jobs}>· {worker.jobs} completed jobs</Text></View><StatusPill label={worker.availability} tone={worker.availability === "Available today" ? "green" : "gray"} /></View></TouchableOpacity>)}</View></ScrollView></AppScreen>;
}

const styles = StyleSheet.create({ content: { padding: 20, paddingTop: 18, paddingBottom: 34, gap: 19, backgroundColor: palette.canvas }, eyebrow: { color: palette.orange, fontFamily: "Inter_700Bold", fontSize: 10, letterSpacing: 1.25 }, title: { fontSize: 28, lineHeight: 35, maxWidth: 335, marginTop: 3 }, subtitle: { maxWidth: 330, marginTop: 8 }, categoryRow: { gap: 8 }, categorySelected: { backgroundColor: palette.blue, borderRadius: 999, paddingHorizontal: 14, paddingVertical: 9 }, category: { backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: palette.border, borderRadius: 999, paddingHorizontal: 14, paddingVertical: 9 }, categorySelectedText: { color: "#FFFFFF", fontFamily: "Inter_700Bold", fontSize: 12 }, categoryText: { color: palette.muted, fontFamily: "Inter_600SemiBold", fontSize: 12 }, liveCard: { padding: 14, borderRadius: 18, backgroundColor: "#FFF5F0", borderWidth: 1, borderColor: "#FFE0D1", flexDirection: "row", alignItems: "center", gap: 10 }, liveIcon: { width: 35, height: 35, borderRadius: 12, backgroundColor: palette.orange, alignItems: "center", justifyContent: "center" }, liveCopy: { flex: 1, gap: 2 }, liveTitle: { color: palette.ink, fontFamily: "Inter_700Bold", fontSize: 13 }, liveMeta: { color: palette.muted, fontFamily: "Inter_400Regular", fontSize: 11, lineHeight: 15 }, list: { gap: 10 }, workerCard: { padding: 14, borderRadius: 20, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: palette.border, flexDirection: "row", gap: 13 }, workerAvatar: { width: 54, height: 54, borderRadius: 19, alignItems: "center", justifyContent: "center" }, workerInitials: { fontFamily: "PlusJakartaSans_800ExtraBold", fontSize: 15 }, verified: { position: "absolute", width: 17, height: 17, borderRadius: 9, right: -2, bottom: -2, alignItems: "center", justifyContent: "center", borderWidth: 2, borderColor: "#FFFFFF" }, workerCopy: { flex: 1, gap: 4 }, workerTop: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, workerName: { color: palette.ink, fontFamily: "Inter_700Bold", fontSize: 14 }, workerSkill: { color: palette.blue, fontFamily: "Inter_600SemiBold", fontSize: 12 }, ratingRow: { flexDirection: "row", alignItems: "center", gap: 3 }, rating: { color: palette.ink, fontFamily: "Inter_700Bold", fontSize: 11 }, jobs: { color: palette.muted, fontFamily: "Inter_400Regular", fontSize: 11 } });
